"""Static skill knowledge base — used when Gemini is offline and for extraction."""
from __future__ import annotations

# Canonical form -> list of aliases/mentions we'll detect in resume text.
SKILL_ALIASES: dict[str, list[str]] = {
    "Python": ["python", "python3"],
    "Java": ["java"],
    "JavaScript": ["javascript", "js", "es6", "ecmascript"],
    "TypeScript": ["typescript", "ts"],
    "C++": ["c++", "cpp"],
    "C#": ["c#", "csharp", ".net", "dotnet"],
    "Go": ["golang", "go lang"],
    "Rust": ["rustlang", "rust"],
    "SQL": ["sql", "mysql", "postgres", "postgresql", "sqlite", "mssql"],
    "NoSQL": ["nosql", "mongodb", "dynamodb", "cassandra"],
    "MongoDB": ["mongodb", "mongo"],
    "PostgreSQL": ["postgresql", "postgres"],
    "Redis": ["redis"],
    "HTML": ["html", "html5"],
    "CSS": ["css", "css3", "scss", "sass"],
    "Tailwind CSS": ["tailwind", "tailwindcss"],
    "React": ["react", "reactjs", "react.js"],
    "Next.js": ["next.js", "nextjs"],
    "Vue.js": ["vue", "vuejs", "vue.js"],
    "Angular": ["angular", "angularjs"],
    "Redux": ["redux"],
    "Node.js": ["node", "nodejs", "node.js"],
    "Express.js": ["express", "expressjs"],
    "FastAPI": ["fastapi"],
    "Flask": ["flask"],
    "Django": ["django"],
    "Spring Boot": ["spring boot", "springboot", "spring"],
    "REST APIs": ["rest", "restful", "rest api"],
    "GraphQL": ["graphql"],
    "gRPC": ["grpc"],
    "Docker": ["docker"],
    "Kubernetes": ["kubernetes", "k8s"],
    "AWS": ["aws", "amazon web services", "ec2", "s3", "lambda"],
    "Azure": ["azure"],
    "GCP": ["gcp", "google cloud"],
    "Terraform": ["terraform"],
    "CI/CD": ["ci/cd", "ci cd", "github actions", "jenkins", "gitlab ci"],
    "Git": ["git", "github", "gitlab", "version control"],
    "Linux": ["linux", "ubuntu", "bash", "shell scripting"],
    "Pandas": ["pandas"],
    "NumPy": ["numpy"],
    "scikit-learn": ["scikit-learn", "sklearn"],
    "TensorFlow": ["tensorflow", "tf"],
    "PyTorch": ["pytorch", "torch"],
    "Hugging Face": ["hugging face", "huggingface", "transformers"],
    "LangChain": ["langchain"],
    "LLMs": ["llm", "large language model", "gpt", "gemini", "claude"],
    "Prompt Engineering": ["prompt engineering", "prompting"],
    "MLOps": ["mlops"],
    "Feature Engineering": ["feature engineering"],
    "Data Visualization": ["data visualization", "matplotlib", "seaborn", "plotly"],
    "Power BI": ["power bi", "powerbi"],
    "Tableau": ["tableau"],
    "Excel": ["excel", "advanced excel"],
    "Statistics": ["statistics", "statistical"],
    "A/B Testing": ["a/b testing", "ab testing", "experimentation"],
    "ETL": ["etl", "elt", "data pipelines"],
    "Apache Spark": ["spark", "pyspark"],
    "Airflow": ["airflow"],
    "Figma": ["figma"],
    "User Research": ["user research", "usability testing"],
    "Wireframing": ["wireframing", "wireframes"],
    "Prototyping": ["prototyping", "prototype"],
    "Design Systems": ["design system", "design systems"],
    "Accessibility": ["accessibility", "a11y", "wcag"],
    "Agile": ["agile", "scrum", "kanban"],
    "Jira": ["jira"],
    "Roadmapping": ["roadmap", "roadmapping", "product roadmap"],
    "Stakeholder Management": ["stakeholder"],
    "Data-Driven Decision Making": ["data-driven", "data driven"],
    "SQL for Analytics": ["sql analytics", "analytics sql"],
    "React Native": ["react native"],
    "Flutter": ["flutter", "dart"],
    "Kotlin": ["kotlin"],
    "Swift": ["swift", "ios development"],
    "Network Security": ["network security"],
    "Penetration Testing": ["penetration testing", "pentest", "pen-test"],
    "OWASP": ["owasp"],
    "SIEM": ["siem", "splunk"],
    "Wireshark": ["wireshark"],
    "Cryptography": ["cryptography", "encryption"],
    "Threat Modeling": ["threat modeling"],
    "Incident Response": ["incident response"],
    "IAM": ["iam", "identity and access"],
    "Problem Solving": ["problem solving"],
    "Communication": ["communication skills", "public speaking"],
    "Teamwork": ["teamwork", "collaboration"],
    "Leadership": ["leadership", "led a team", "mentorship", "mentoring"],
    # extras to boost recall
    "Firebase": ["firebase", "firestore"],
    "Supabase": ["supabase"],
    "Vercel": ["vercel"],
    "Netlify": ["netlify"],
    "Next.js": ["next.js", "nextjs", "next js"],
    "Svelte": ["svelte", "sveltekit"],
    "Nuxt": ["nuxt", "nuxt.js"],
    "Remix": ["remix.run", "remix framework"],
    "Nest.js": ["nest.js", "nestjs"],
    "OAuth": ["oauth", "oauth2"],
    "JWT": ["jwt", "json web token"],
    "WebSockets": ["websocket", "websockets", "socket.io"],
    "Kafka": ["kafka", "apache kafka"],
    "RabbitMQ": ["rabbitmq", "rabbit mq"],
    "Elasticsearch": ["elasticsearch", "elastic search"],
    "CI/CD Pipelines": ["github actions", "gitlab ci", "circleci", "jenkins"],
    "Jenkins": ["jenkins"],
    "Ansible": ["ansible"],
    "Grafana": ["grafana"],
    "Prometheus": ["prometheus"],
    "OpenTelemetry": ["opentelemetry", "otel"],
    "Datadog": ["datadog"],
    "Snowflake": ["snowflake"],
    "BigQuery": ["bigquery"],
    "dbt": ["dbt", "data build tool"],
    "Looker": ["looker", "looker studio", "data studio"],
    "Streamlit": ["streamlit"],
    "Gradio": ["gradio"],
    "RAG": ["rag", "retrieval-augmented generation"],
    "Vector Databases": ["pinecone", "weaviate", "chroma", "qdrant"],
    "OpenAI API": ["openai", "openai api", "gpt-4", "chatgpt api"],
    "Anthropic API": ["anthropic api", "claude api"],
    "Gemini API": ["gemini api", "google ai"],
    "Solidity": ["solidity"],
    "Ethereum": ["ethereum", "evm"],
    "Web3": ["web3", "web3.js", "ethers.js"],
    "Smart Contracts": ["smart contracts"],
    "Unity": ["unity", "unity3d"],
    "Unreal Engine": ["unreal engine", "unreal"],
    "C": ["embedded c", " c "],
    "Embedded Systems": ["embedded", "microcontroller"],
    "Arduino": ["arduino"],
    "Raspberry Pi": ["raspberry pi"],
    "RTOS": ["rtos", "freertos"],
    "Selenium": ["selenium"],
    "Cypress": ["cypress"],
    "Playwright": ["playwright"],
    "Jest": ["jest"],
    "Pytest": ["pytest"],
    "JUnit": ["junit"],
    "API Testing": ["postman", "api testing"],
    "Load Testing": ["jmeter", "load testing", "k6"],
    "Technical Writing": ["technical writing", "documentation"],
    "SEO": ["seo"],
    "Content Strategy": ["content strategy"],
}


def canonical_skill_list() -> list[str]:
    return list(SKILL_ALIASES.keys())
