import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { GapAnalysis, Roadmap, Role } from "../types";

export function exportRoadmapPdf(opts: {
  gap: GapAnalysis;
  roadmap: Roadmap;
  role: Role;
  hoursPerWeek: number;
}) {
  const { gap, roadmap, role, hoursPerWeek } = opts;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 40;
  let y = margin;

  // --- header ---
  doc.setFillColor(109, 40, 217);
  doc.rect(0, 0, 595.28, 70, "F");
  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("SkillBridge AI — Your Roadmap", margin, 45);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Role: ${role.title}  |  ${hoursPerWeek} hrs/week  |  Score: ${gap.readiness_score}%`, margin, 62);
  y = 100;

  // --- overview ---
  doc.setTextColor(20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Overview", margin, y); y += 16;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(70);
  const ovLines = doc.splitTextToSize(roadmap.overview, 515);
  doc.text(ovLines, margin, y);
  y += ovLines.length * 14 + 8;

  // --- gap summary ---
  autoTable(doc, {
    startY: y,
    theme: "grid",
    head: [["Matched", "Weak", "Missing", "Weeks to ready"]],
    body: [[
      String(gap.matched.length),
      String(gap.weak.length),
      String(gap.missing.length),
      String(gap.weeks_to_ready),
    ]],
    headStyles: { fillColor: [79, 70, 229], textColor: 255, halign: "center" },
    bodyStyles: { halign: "center", fontSize: 11 },
    styles: { cellPadding: 6 },
  });
  // @ts-expect-error plugin adds lastAutoTable
  y = doc.lastAutoTable.finalY + 16;

  // --- weeks ---
  roadmap.weeks.forEach((w) => {
    if (y > 760) { doc.addPage(); y = margin; }
    doc.setTextColor(109, 40, 217);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(`Week ${w.week} — ${w.focus}`, margin, y); y += 15;

    doc.setTextColor(60);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const why = doc.splitTextToSize(`Why: ${w.why_it_matters}`, 515);
    doc.text(why, margin, y);
    y += why.length * 12 + 2;
    doc.text(`Commitment: ${w.daily_commitment}`, margin, y); y += 14;

    autoTable(doc, {
      startY: y,
      theme: "plain",
      head: [["Resource", "Type", "Duration"]],
      body: w.resources.map((r) => [
        `${r.name}\n${r.url}`,
        r.type,
        r.duration || "—",
      ]),
      headStyles: { fillColor: [237, 233, 254], textColor: [46, 16, 101], fontStyle: "bold" },
      bodyStyles: { fontSize: 9, textColor: 50, cellPadding: 4, valign: "top" },
      columnStyles: { 0: { cellWidth: 330 }, 1: { cellWidth: 80 }, 2: { cellWidth: 80 } },
    });
    // @ts-expect-error plugin adds lastAutoTable
    y = doc.lastAutoTable.finalY + 8;

    if (y > 760) { doc.addPage(); y = margin; }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(20);
    doc.text("Project:", margin, y); y += 12;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60);
    const proj = doc.splitTextToSize(`${w.project.title}: ${w.project.description}`, 515);
    doc.text(proj, margin, y);
    y += proj.length * 12 + 6;

    doc.setFont("helvetica", "italic");
    doc.setTextColor(46, 16, 101);
    const mile = doc.splitTextToSize(`Milestone: ${w.milestone}`, 515);
    doc.text(mile, margin, y);
    y += mile.length * 12 + 16;
  });

  // --- footer ---
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setTextColor(140);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Generated by SkillBridge AI · page ${i}/${pages}`,
      margin,
      doc.internal.pageSize.getHeight() - 20
    );
  }

  doc.save(`skillbridge-${role.id}-roadmap.pdf`);
}
